SELECT * FROM ChicagoCrimeData; 
SELECT * FROM ChicagoPublicSchools; 
SELECT * FROM ChicagoCensusData
;
-- COUNT OF EACH CRIME. 
SELECT PRIMARY_TYPE, 
	COUNT (PRIMARY_TYPE) AS CRIME_COMMITED
FROM ChicagoCrimeData
GROUP BY PRIMARY_TYPE
ORDER BY CRIME_COMMITED DESC

-- WHICH LOCATION HAS THE MOST CRIME. 
SELECT COMMUNITY_AREA_NUMBER, PRIMARY_TYPE,
	COUNT (PRIMARY_TYPE) AS CRIME_COMMITED
FROM ChicagoCrimeData
WHERE COMMUNITY_AREA_NUMBER IS NOT NULL
GROUP BY PRIMARY_TYPE, COMMUNITY_AREA_NUMBER
ORDER BY CRIME_COMMITED DESC

-- WHICH TOP 5 COMMUNITY AREA HAS THE MOST NARCOTIC CRIMES. 
SELECT TOP 5 COMMUNITY_AREA_NUMBER, 
	COUNT (PRIMARY_TYPE) AS NARC
FROM ChicagoCrimeData
WHERE PRIMARY_TYPE = 'NARCOTICS' 
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY NARC DESC 

-- WHICH SCHOOL HAS THE MOST CRIME AROUND. (JOIN)
SELECT ChicagoPublicSchools.NAME_OF_SCHOOL,
	CHICAGOCRIMEDATA.PRIMARY_TYPE, 
	COUNT (CHICAGOCRIMEDATA.PRIMARY_TYPE) AS TOTAL_CRIMES
FROM ChicagoCrimeData
	JOIN ChicagoPublicSchools
	ON ChicagoCrimeData.COMMUNITY_AREA_NUMBER = ChicagoPublicSchools.COMMUNITY_AREA_NUMBER
GROUP BY ChicagoCrimeData.PRIMARY_TYPE, ChicagoPublicSchools.NAME_OF_SCHOOL
ORDER BY TOTAL_CRIMES DESC

-- WHICH COMMUNITY HAS THE MOST TORUBLE. (CENSUS)
SELECT ChicagoPublicSchools.COMMUNITY_AREA_NAME, 
	ChicagoCrimeData.PRIMARY_TYPE,
	ChicagoCensusData.PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,
	ChicagoCensusData.PERCENT_AGED_16__UNEMPLOYED
FROM ChicagoCrimeData
	JOIN ChicagoPublicSchools
	ON ChicagoCrimeData.COMMUNITY_AREA_NUMBER = ChicagoPublicSchools.COMMUNITY_AREA_NUMBER
	JOIN ChicagoCensusData
	ON ChicagoCensusData.COMMUNITY_AREA_NUMBER = ChicagoCrimeData.COMMUNITY_AREA_NUMBER
ORDER BY PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA DESC; 

-- TOTAL CRIMES COMMIITED, DUE TO HARDSHIP_INDEX AND FAMILY INVOLVMENT? 
SELECT ChicagoPublicSchools.COMMUNITY_AREA_NAME,
	CHICAGOCRIMEDATA.PRIMARY_TYPE,
	COUNT (ChicagoCrimeData.PRIMARY_TYPE) AS TOTAL_CRIME_TYPE,
	ChicagoCensusData.HARDSHIP_INDEX,
	ChicagoPublicSchools.Family_Involvement_Score
FROM ChicagoCrimeData
	JOIN ChicagoPublicSchools
	ON ChicagoCrimeData.COMMUNITY_AREA_NUMBER = ChicagoPublicSchools.COMMUNITY_AREA_NUMBER
	JOIN ChicagoCensusData
	ON ChicagoCensusData.COMMUNITY_AREA_NUMBER = ChicagoPublicSchools.COMMUNITY_AREA_NUMBER
WHERE ChicagoPublicSchools.Family_Involvement_Score IS NOT NULL AND HARDSHIP_INDEX > 50
GROUP BY ChicagoCrimeData.PRIMARY_TYPE, 
	ChicagoCensusData.HARDSHIP_INDEX, 
	ChicagoPublicSchools.COMMUNITY_AREA_NAME, 
	ChicagoPublicSchools.Family_Involvement_Score
HAVING COUNT (*) > 5
ORDER BY TOTAL_CRIME_TYPE DESC

--CRIMES COMMITTED ON SCHOOL GROUNDS. 
SELECT LOCATION_DESCRIPTION, 
	PRIMARY_TYPE, DESCRIPTION
FROM ChicagoCrimeData
WHERE LOCATION_DESCRIPTION LIKE 'SCHOOL%'

-- HOW MANY CRIMES BY AREA. 
SELECT ChicagoPublicSchools.COMMUNITY_AREA_NAME,
	CHICAGOCRIMEDATA.PRIMARY_TYPE,
	COUNT (CHICAGOCRIMEDATA.PRIMARY_TYPE) AS TOTAL_CRIMES,
	ChicagoCrimeData.LOCATION_DESCRIPTION
FROM ChicagoCrimeData
	JOIN ChicagoPublicSchools
	ON ChicagoCrimeData.COMMUNITY_AREA_NUMBER = ChicagoPublicSchools.COMMUNITY_AREA_NUMBER
GROUP BY ChicagoCrimeData.PRIMARY_TYPE, ChicagoCrimeData.LOCATION_DESCRIPTION, ChicagoPublicSchools.COMMUNITY_AREA_NAME
ORDER BY TOTAL_CRIMES DESC; 

-- CRIMES IN AREA FROM KIDS NOT IN COLLEGE.
SELECT ChicagoCrimeData.PRIMARY_TYPE,
	COUNT (CHICAGOCRIMEDATA.PRIMARY_TYPE) AS TOTAL_CRIMES,
	ChicagoCensusData.PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA
FROM ChicagoCrimeData
	JOIN ChicagoCensusData
	ON ChicagoCrimeData.COMMUNITY_AREA_NUMBER = ChicagoCensusData.COMMUNITY_AREA_NUMBER
GROUP BY ChicagoCrimeData.PRIMARY_TYPE, ChicagoCensusData.PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA
HAVING COUNT (*) > 2
ORDER BY PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA DESC

-- AREA WITH THE THEFT CRIMES.
SELECT TOP 5 
	ChicagoPublicSchools.COMMUNITY_AREA_NAME,
	ChicagoCrimeData.PRIMARY_TYPE,
	COUNT (ChicagoCrimeData.PRIMARY_TYPE) AS TOTAL_THEFTS
FROM ChicagoCrimeData
	JOIN ChicagoPublicSchools
	ON ChicagoCrimeData.COMMUNITY_AREA_NUMBER = ChicagoPublicSchools.COMMUNITY_AREA_NUMBER
WHERE PRIMARY_TYPE = 'THEFT' 
GROUP BY ChicagoPublicSchools.COMMUNITY_AREA_NAME, ChicagoCrimeData.PRIMARY_TYPE
ORDER BY TOTAL_THEFTS DESC

--MATCH AREA NUMBER WITH AREA NAME. 
SELECT ChicagoPublicSchools.COMMUNITY_AREA_NAME,
	ChicagoCensusData.COMMUNITY_AREA_NUMBER
FROM ChicagoPublicSchools
	JOIN ChicagoCensusData
	ON ChicagoCensusData.COMMUNITY_AREA_NAME = ChicagoPublicSchools.COMMUNITY_AREA_NAME
GROUP BY ChicagoPublicSchools.COMMUNITY_AREA_NAME, ChicagoCensusData.COMMUNITY_AREA_NUMBER
ORDER BY COMMUNITY_AREA_NUMBER 
 
-- CITY WITH THE MOST CRIMES. 
SELECT TOP 3 
	COMMUNITY_AREA_NUMBER, 
	COUNT (PRIMARY_TYPE) TOTAL_CRIMES
FROM ChicagoCrimeData
WHERE COMMUNITY_AREA_NUMBER IS NOT NULL
GROUP BY COMMUNITY_AREA_NUMBER 
ORDER BY TOTAL_CRIMES DESC

-- HUMAN TRAFFCIKING CRIMES. (DOUBLE CHECK WITH COUNT)
SELECT PRIMARY_TYPE, DESCRIPTION, LOCATION_DESCRIPTION
FROM ChicagoCrimeData
WHERE PRIMARY_TYPE = 'HUMAN TRAFFICKING'; 

SELECT COUNT (PRIMARY_TYPE) AS H_F
FROM ChicagoCrimeData
WHERE PRIMARY_TYPE LIKE '%TRAFFICKING';


